### 用户注册

POST http://localhost:8888/user/userLogin/register HTTP/1.1
Content-Type: application/json

{
    "userName": "stone_elm",
    "password": "Super@123..++",
    "nickName": "管理员",
    "userPhone": "17600943691"
}

### 用户登录

POST http://localhost:8888/user/userLogin/login HTTP/1.1
Content-Type: application/json

{
    "userName": "stone_elm",
    "password": "Super@123..++",
    "loginModel": "01"
}

### 查询标准代码分类

POST http://localhost:8888/system/codeCls/queryCodeClsList HTTP/1.1
Content-Type: application/json
Stone-Token: eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiI0MGMxOThiNDgzYTM0NTg4OGZiOTc4YjZhMjA0MzgwZiIsInN1YiI6IjQiLCJpc3MiOiJzdG9uZSIsImlhdCI6MTcyMDU5NDQwNiwiZXhwIjoxNzIwNTk4MDA2fQ.O9ZZ2qYf2iVKGli8VUAL13uo0_P7iFeCE6cfjAIAlSg

{  
    
}